spring:
  application:
    name: user-service
  mongodb:
    uri: mongodb://user-mongo:27017/users

server:
  port: 8080

jwt:
  token-cookie-expiration: 604800
  token-name: JWT_token
  token-expiration: 604800000
  one-day-in-ms: 86400000
  key: my-super-super-secret-key-which-is-very-long-1234

url:
  logout-url: http://localhost:5173/
