spring.application.name=user-service

server.port=8082

spring.mongodb.uri=mongodb://localhost:27017/users

jwt.token-cookie-expiration=604800
jwt.token-name=JWT_token
jwt.token-expiration=604800000
jwt.one-day-in-ms=86400000
url.logout-url=http://localhost:5173/
