services:
  user-mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - user-mongo-data:/data/db

  shopping-list-mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - shopping-list-mongo-data:/data/db

  user-service:
    build: ../services/user-service
    depends_on:
      - user-mongo

  shopping-list-service:
    build: ../services/shopping-list-service
    depends_on:
      - shopping-list-mongo

  gateway:
    build: ../gateway
    depends_on:
      - shopping-list-service
      - user-service
    ports:
      - "8080:8080"

  frontend:
    build: ../frontend
    depends_on:
      - gateway
    ports:
      - "4200:4200"
    volumes:
      - ../frontend:/app
      - /app/node_modules

volumes:
  user-mongo-data:
  shopping-list-mongo-data: