services:
  user-mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - user-mongo-data:/data/db

  shopping-list-mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - shopping-list-mongo-data:/data/db

volumes:
  user-mongo-data:
  shopping-list-mongo-data: