server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://user-service:8080
              predicates:
                - Path=/auth/**

            - id: shopping-list-service
              uri: http://shopping-list-service:8080
              predicates:
                - Path=/shoppings/lists/**

jwt:
  key: my-super-super-secret-key-which-is-very-long-1234